/*
===============================================================================
File Name: magnitude_analysis.sql
===============================================================================

Purpose:
    - To measure business performance across different dimensions.
    - To analyze customer, product, sales, and geographic distributions.
    - To identify high-performing categories, customers, and regions.

Business Questions Answered:
    - Which countries have the most customers?
    - Which product categories generate the most revenue?
    - Which customers contribute the highest sales?
    - How are products distributed across categories?
    - What are the sales patterns across countries?

SQL Functions Used:
    - SUM(), COUNT(), AVG(), DISTINCT
    - GROUP BY, ORDER BY
===============================================================================
*/


-- ============================================================================
-- Total Customers by Country
-- ============================================================================
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- ============================================================================
-- Total Customers by Gender
-- ============================================================================
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- ============================================================================
-- Total Products by Category
-- ============================================================================
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- ============================================================================
-- Average Product Cost by Category
-- ============================================================================
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- ============================================================================
-- Product Count by Subcategory
-- ============================================================================
SELECT
    category,
    subcategory,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category, subcategory
ORDER BY category, total_products DESC;


-- ============================================================================
-- Total Revenue Generated by Each Product Category
-- ============================================================================
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
       ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- ============================================================================
-- Total Revenue Generated by Each Customer
-- ============================================================================
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
       ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


-- ============================================================================
-- Top 10 Highest Revenue Customers
-- ============================================================================
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
       ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


-- ============================================================================
-- Distribution of Sold Items Across Countries
-- ============================================================================
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
       ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;


-- ============================================================================
-- Total Revenue by Country
-- ============================================================================
SELECT
    c.country,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
       ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_revenue DESC;


-- ============================================================================
-- Average Revenue per Order by Category
-- ============================================================================
SELECT
    p.category,
    AVG(f.sales_amount) AS avg_order_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
       ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY avg_order_revenue DESC;


-- ============================================================================
-- Total Quantity Sold by Product Category
-- ============================================================================
SELECT
    p.category,
    SUM(f.quantity) AS total_quantity_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
       ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_quantity_sold DESC;